---
- name: copy filebeat.deb
  ansible.builtin.get_url:
    url: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/f/filebeat/filebeat-8.10.3-amd64.deb
    dest: /tmp

- name: install filebeat
  ansible.builtin.apt:
    deb: "/tmp/filebeat-8.10.3-amd64.deb"

- name: replace config file
  template:
    src: templates/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify:
    - enable filebeat

- name: start filebeat
  ansible.builtin.systemd_service:
    daemon_reload: yes
    enabled: yes
    state: started
    name: filebeat.service

- name: Return service state information as fact data
  service_facts:

- name: Show the status of filebeat service
  debug:
    var: ansible_facts.services['filebeat.service']['state']