---
- name: Install reqs for Docker
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: yes

- name: Install prerequisites
  apt:
    name: [ca-certificates, curl, gnupg]
    state: present
    update_cache: yes

- name: Add Docker GPG key (alternative way)
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker-ce

- name: Update and install docker
  ansible.builtin.apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: docker systemd
  ansible.builtin.systemd_service:
    daemon_reload: yes
    enabled: yes
    state: started
    name: docker

- name: Install the Docker module for Python
  apt:
    name: python3-docker

- name: Create dir for data
  ansible.builtin.file:
    path: /etc/elasticsearch/data
    state: directory
    owner: 1000
    group: 1000
    mode: 0775

- name: Create container
  docker_container:
    name: "Elasticsearch"
    image: "bitnami/elasticsearch:latest"
    user: 1000
    volumes:
    - "/etc/elasticsearch/data:/bitnami/elasticsearch/data"
    ports:
    - "9200:9200"
    - "9300:9300"
    env:
        ELASTICSEARCH_CLUSTER_NAME=gorelov-coursework
        xpack.security.enrollment.enabled=true
    state: started
    restart_policy: always

- name: docker container ls -la
  tags: container_ls
  shell: "docker container ls -la"
  register: container_info
  
- name: docker container ls -la result
  tags: container_ls
  debug:
    msg: "{{container_info.stdout_lines}}"