---
- name: Create Prometheus user
  user:
    name: prometheus
    system: yes
    shell: /usr/sbin/nologin

- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.37.0/prometheus-2.37.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Create config directory
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: Copy Prometheus config
  template:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus

- name: Create systemd service
  template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Reload systemd and start Prometheus
  systemd:
    daemon_reload: yes
    name: prometheus
    state: started
    enabled: yes