---
- name: docker systemd
  ansible.builtin.systemd_service:
    daemon_reload: yes
    enabled: yes
    state: started
    name: docker
    
- name: node-exporter systemd
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: prometheus-node-exporter.service